# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suiji.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.all_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.all_lineEdit.setObjectName("all_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.all_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.check_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.check_lineEdit.setObjectName("check_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.check_lineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dataTextEdit.setObjectName("dataTextEdit")
        self.horizontalLayout.addWidget(self.dataTextEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stratButton = QtWidgets.QPushButton(self.centralwidget)
        self.stratButton.setObjectName("stratButton")
        self.verticalLayout.addWidget(self.stratButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataButton.setObjectName("dataButton")
        self.verticalLayout.addWidget(self.dataButton)
        self.outButton = QtWidgets.QPushButton(self.centralwidget)
        self.outButton.setObjectName("outButton")
        self.verticalLayout.addWidget(self.outButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "总人数"))
        self.label_2.setText(_translate("MainWindow", "抽样人数"))
        self.stratButton.setText(_translate("MainWindow", "开始"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.dataButton.setText(_translate("MainWindow", "显示"))
        self.outButton.setText(_translate("MainWindow", "退出"))
